#coding:utf-8

import unittest
from unittest_test1 import MyTest

from HTMLTestRunner import HTMLTestRunner

if __name__ == '__main__':
    suite = unittest.TestSuite()
 
    tests = [MyTest("test_a_run"), MyTest("test_b_run")]
    suite.addTests(tests)
 
    with open('UnittestTextReport.html', 'a') as  f:
        runner = HTMLTestRunner(stream=f,
                                title = 'my Test Report',
                                description='generated by HTMLTestRunner.',
                                verbosity=2
                                )
        runner.run(suite)

